# theme: jekyll-theme-minimal
# remote_theme: mmistakes/minimal-mistakes
# remote_theme: jekyll-theme-primer
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-include-cache
  - jekyll-feed
