# theme: jekyll-theme-minimal
# remote_theme: mmistakes/minimal-mistakes
# remote_theme: jekyll-theme-primer
remote_theme: mattvh/jekyll-theme-console
plugins:
  - jekyll-include-cache
  - jekyll-feed
