# remote_theme: mmistakes/minimal-mistakes
# remote_theme: barryclark/jekyll-now
# remote_theme: johno/pixyll
# remote_theme: academicpages/academicpages.github.io
remote_theme: elotroalex/ed
# plugins:
#   - jekyll-include-cache
#   - jekyll-archives
